// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using importExcelMvc.Data;

namespace importExcelMvc.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("importExcelMvc.Data.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Condominio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new { Id = 1, Condominio = "RESIDENCIAL JK", Endereco = "ST. SAGOCAN LT. 2 RES. JK BL. C APTO. 701", Nome = "Fulano de Tal da Silva Sauro", Telefone = "6197745120" },
                        new { Id = 2, Condominio = "RESIDENCIAL ESPLANADA", Endereco = "ST. SAGOCAN LT. 3 RES. ESPLANADA BL. A APTO. 1101", Nome = "Rosicleide Morais Oliveira Costa e Silva", Telefone = "61983325471" },
                        new { Id = 3, Condominio = "ESTÂNCIA QUINTAS DA ALVORADA", Endereco = "SHJB COND. ESTÂNCIA QUINTAS DA ALVORADA RUA 5 CASA 23", Nome = "Basília Rodrigues de Sá", Telefone = "6132050411" },
                        new { Id = 4, Condominio = "ESTÂNCIA QUINTAS DA ALVORADA", Endereco = "SHJB COND. ESTÂNCIA QUINTAS DA ALVORADA RUA 12 CASA 6", Nome = "Virgolina Inácia Pereira dos Montes", Telefone = "61982475151" },
                        new { Id = 5, Condominio = "CONDOMÍNIO POR DO SOL", Endereco = "AOS 7 BL. A APTO. 16, ÁREA OCTOGONAL, CRUZEIRO", Nome = "Balbino Diniz de Oliveira Conde", Telefone = "61984217140" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
